os: linux
arch: arm64
language: cpp
services:
  - docker
env:
  - PKG=fog05 VERSION=0.2.1 BRANCH=0.2.x IMAGE=fog05/ubuntu-build:arm64
  - PKG=fog05-plugin-os-linux VERSION=0.2.0 BRANCH=0.2.x
  - PKG=fog05-plugin-net-linuxbridge VERSION=0.2.1 BRANCH=0.2.x
  - PKG=fog05-plugin-fdu-native VERSION=0.2.0 BRANCH=0.2.x
  - PKG=fog05-plugin-fdu-ros2 VERSION=0.2.0 BRANCH=0.2.x
  - PKG=fog05-plugin-fdu-kvm VERSION=0.2.0 BRANCH=0.2.x
  - PKG=fog05-plugin-fdu-lxd VERSION=0.2.1 BRANCH=0.2.x
  - PKG=fog05-plugin-fdu-containerd VERSION=0.2.0 BRANCH=0.2.x
  - PKG=zenoh VERSION=0.3.0 BRANCH=0.3.0 IMAGE=fog05/ubuntu-build:arm64
  - PKG=libzenoh VERSION=0.3.0 BRANCH=0.3.0 IMAGE=ubuntu:bionic
  - PKG=containerd VERSION=1.3.2 BRANCH=v1.3.2 IMAGE=ubuntu:bionic
script: bash -ex build_debs.shß